# Generated by Django 5.0.6 on 2024-05-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_article_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='TITLE',
            new_name='HEADING',
        ),
    ]
