# Generated by Django 5.0.6 on 2024-05-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_user_alter_article_heading_alter_article_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('editor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('editor_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.CharField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('Publisher_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='PASSWORD',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.CharField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('journal_name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('Editor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.editor')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.publisher')),
            ],
        ),
    ]
