# Generated by Django 5.0.6 on 2024-05-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_editor_publisher_alter_user_password_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='JOURNAL_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.journal'),
        ),
    ]
